languageCode: pl-pl
title: Mikołaj Młodzikowski
theme: retroful
publishdir: ../public
pygmentsUseClasses: true
Params:
  subtitle: ''
  logo: img/logo.jpg
  favicon: img/fav.ico
Author:
  handle: Mikołaj Młodzikowski
  bitbucket: mkjmdski
  github: mkjmdski
  linkedin: in/mlodzikowski
menu:
  main:
    - name: DigitalOcean Referal
      url: 'https://m.do.co/c/21d96d6ebff2'
      weight: 1
