languageCode: pl-pl
title: Mikołaj Młodzikowski
theme: retroful
publishdir: ../public
pygmentsUseClasses: true
Params:
  subtitle: ''
  logo: img/logo.jpg
  favicon: img/fav.ico
Author:
  handle: Mikołaj Młodzikowski
  bitbucket: mkjmdski
  github: mkjmdski
  linkedin: in/mlodzikowski
menu:
  main:
    - name: CV
      url: 'https://mlodzikowski.pl/cv'
      weight: 10