language: go
sudo: required
services:
  - docker
script:
  - ./build_dist.sh
  - ./build_api.sh
branches:
  only:
    - master
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $github_token
  keep-history: true
  target-branch: production
  verbose: true
  on:
    branch: master
notifications:
    slack:
      rooms:
        - $slack_access
      on_success: always
      on_failure: always