services:
  - docker
language: go
script:
  - bash build_dist.sh
branches:
  only:
    - master
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $github_token
    keep-history: true
    local-dir: production
    target-branch: production
    verbose: true
    on:
      branch: master
  - provider: script
    script: curl -X POST -d {} $netlify_hook