sudo: required
services:
  - docker
script:
  - ./build_dist.sh
branches:
  only:
    - master
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $github_token
  keep-history: true
  local-dir: public
  target-branch: production
  verbose: true
  on:
    branch: master