sudo: required
services:
  - docker
script:
  - make
branches:
  only:
    - develop
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $github_token
  keep-history: true
  local-dir: public
  target-branch: master
  verbose: true
  on:
    branch: develop