# Site configuration
menu:
  main:
    - name: Blog
      weight: 1
      url: /posts/
    - name: About
      weight: 2
      url: /about/
    - name: Projects
      weight: 3
      url: /projects/
    - name: Contact me
      weight: 5
      url: /contact/

tagline: &tagline
  - name: DevOps Enthusiast
    fabIcon: fa-docker
  - name: Build Automation
    fabIcon: fa-jenkins
  - name: Linux Lover
    fabIcon: fa-linux

quickLinks: &quickLinks
  - name: Introduction to terraform
    href: /terraform
    title: Presentation from SysOps/DevOps Polska meetup
  - name: About configuring ZSH
    href: https://blog.apptension.com/2018/08/30/shell-configuration-hack-your-zsh/
    title: Article from apptension blog
  - name: DigitalOcean referal link 100$
    href: https://m.do.co/c/21d96d6ebff2
    title: Use this link to signup on DigitalOcean with 100$

social: &social
  - name: Github
    icon: fa-github
    weight: 1
    url: https://github.com/mkjmdski/
  - name: LinkedIn
    icon: fa-linkedin
    weight: 2
    url: https://www.linkedin.com/in/mlodzikowski/
  - name: Bitbucket
    icon: fa-bitbucket
    weight: 3
    url: https://bitbucket.org/mkjmdski

# Hugo configuration
baseurl: 'https://mlodzikowski.pl'
title: Mikołaj Młodzikowski
theme: coder
languagecode: en
paginate: 20
canonifyurls: true
pygmentsstyle: dracula
pygmentscodefences: true
pygmentscodefencesguesssyntax: true
disqusShortname: mlodzikowski
params:
  author: '"MikoSoft" Mikołaj Młodzikowski'
  title: Hello, I'm Miko!
  description: Mikołaj's personal website
  keywords: devops,linux,developer,blog
  avatarurl: images/avatar.jpg
  tagline: *tagline
  quickLinks: *quickLinks
  social: *social
  hideCredits: true
