version: "3.4"
services:
  server:
    build:
      context: site
      target: local_server
      args:
        baseURL: &baseURL 'http://localhost.test'
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    environment:
      baseURL: *baseURL