version: "3.4"
services:
  server:
    build:
      context: site
      target: local_server
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    volumes:
      - ./site:/site
    environment:
      baseURL: 'http://localhost.test'