baseURL = "https://mlodzikowski.pl/presentations"
languageCode = "en-us"
title = "My New Hugo Site"
publishdir = "../public/presentations"
theme = "reveal"

[params.reveal_hugo]
custom_theme = "/indigo.css"
reveal_cdn = "https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.7.0"
highlight_cdn = "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0"
highlight_theme = "solarized-dark"

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true
