baseURL: https://mlodzikowski.pl/presentations
languageCode: en-us
title: Mikołaj Młodzikowski DevOps presentations
publishdir: ../public/presentations
theme: reveal
params:
  reveal_hugo:
    custom_theme: /themes/indigo.css
    reveal_cdn: 'https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.7.0'
    highlight_cdn: 'https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0'
    highlight_theme: styles/tomorrow-night-bright
outputFormats:
  Reveal:
    baseName: index
    mediaType: text/html
    isHTML: true
